# Generated by Django 2.0 on 2018-01-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicionario', '0002_auto_20180128_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word_cr',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_en',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_pt',
            field=models.CharField(max_length=60),
        ),
    ]
