# Generated by Django 2.0 on 2018-01-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicionario', '0003_auto_20180128_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word_cr',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_pt',
            field=models.TextField(),
        ),
    ]
